### ISSUE TITLE
QGIS crash on start

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#62]
```
Process:               QGIS [9273]
Path:                  /Applications/QGIS3.4.4.app/Contents/MacOS/QGIS
Identifier:            org.qgis.qgis344
Version:               3.4.4 (3.4.4 [])
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           QGIS [9273]
User ID:               501

Date/Time:             2019-02-13 09:59:57.940 +0000
OS Version:            Mac OS X 10.14.3 (18D109)
Report Version:        12
Bridge OS Version:     3.0 (14Y674)
Anonymous UUID:        C83DD772-2062-6632-9F1F-1DCB7AE37102

Sleep/Wake UUID:       ED7D10DA-56BA-416B-87F6-83FF3D62839C

Time Awake Since Boot: 5800 seconds
Time Since Wake:       4600 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/QtWebKit.framework/QtWebKit
  Referenced from: /Applications/QGIS3.4.4.app/Contents/MacOS/QGIS
  Reason: image not found

Binary Images:
       0x107f56000 -        0x108414ff7 +org.qgis.qgis344 (3.4.4 - 3.4.4 []) <25CBDC19-FAA1-3335-83A4-D8B27622636D> /Applications/QGIS3.4.4.app/Contents/MacOS/QGIS
       0x108436000 -        0x108c17ff3 +libqgis_app.3.4.4.dylib (0) <5D766B5A-DBC5-34B0-9DEE-333CB946CD63> /Applications/QGIS3.4.4.app/Contents/MacOS/lib/libqgis_app.3.4.4.dylib
       0x108f37000 -        0x1095b7fff +org.qgis.qgis3_gui (3.4.4 - qgis_gui 3.4.4) <B27EA93F-CFBC-33A8-99D7-D8800969245D> /Applications/QGIS3.4.4.app/Contents/Frameworks/qgis_gui.framework/Versions/3.4/qgis_gui
       0x109947000 -        0x109a02ff3 +com.yourcompany.qwt (6.1 - 6.1.3) <A14E0E54-55F0-3714-8F31-2197F1D2BD06> /Applications/QGIS3.4.4.app/Contents/Frameworks/qwt.framework/Versions/6/qwt
       0x109a78000 -        0x109c7dffb +libqscintilla2_qt5.13.dylib (0) <FCA879C5-F8C3-3242-9BD8-6A9BB5565B75> /Applications/QGIS3.4.4.app/Contents/MacOS/lib/libqscintilla2_qt5.13.dylib
       0x109cd8000 -        0x109ce3ff7 +org.qt-project.QtQuickWidgets (5.12 - 5.12.0) <B229DA6B-A619-3360-9292-281838E0CF01> /Applications/QGIS3.4.4.app/Contents/Frameworks/QtQuickWidgets.framework/Versions/5/QtQuickWidgets
       0x109cf8000 -        0x109fdbff3 +org.qt-project.QtQuick (5.12 - 5.12.0) <147E8953-83C9-3718-96AD-CC2A86EA22BD> /Applications/QGIS3.4.4.app/Contents/Frameworks/QtQuick.framework/Versions/5/QtQuick
       0x10a0f2000 -        0x10a462ff3 +org.qt-project.QtQml (5.12 - 5.12.0) <17F60C06-AA14-312F-99E0-FE9E2425653C> /Applications/QGIS3.4.4.app/Contents/Frameworks/QtQml.framework/Versions/5/QtQml
       0x10a51e000 -        0x10a6b3ff7 +org.qgis.qgis3_analysis (3.4.4 - qgis_analysis 3.4.4) <8401E4DA-7A17-385B-9A0B-125FD46D83DD> /Applications/QGIS3.4.4.app/Contents/Frameworks/qgis_analysis.framework/Versions/3.4/qgis_analysis
       0x10a78c000 -        0x10a7d7ff3 +org.qgis.qgis3_3d (3.4.4 - qgis_3d 3.4.4) <D9324D87-AA74-32B7-9F2B-F4E3916ACFF8> /Applications/QGIS3.4.4.app/Contents/Frameworks/qgis_3d.framework/Versions/3.4/qgis_3d
       0x10a821000 -        0x10b2edff7 +org.qgis.qgis3_core (3.4.4 - qgis_core 3.4.4) <D22A49DD-27A0-3E37-A4C7-75B3B47FDFC3> /Applications/QGIS3.4.4.app/Contents/Frameworks/qgis_core.framework/Versions/3.4/qgis_core
       0x10b7e5000 -        0x10b7eaff7 +org.qgis.qgis3_native (3.4.4 - qgis_native 3.4.4) <B820BB59-1FBA-34C9-8895-728D49909B92> /Applications/QGIS3.4.4.app/Contents/Frameworks/qgis_native.framework/Versions/3.4/qgis_native
       0x10b7f8000 -        0x10b800ffb +org.qt-project.QtMacExtras (5.12 - 5.12.0) <848D5774-D8E5-34C8-A4F5-7D5845699AEA> /Applications/QGIS3.4.4.app/Contents/Frameworks/QtMacExtras.framework/Versions/5/QtMacExtras
       0x10b810000 -        0x10b831ff7 +org.qt-project.QtSql (5.12 - 5.12.0) <FED6B04A-7385-3F01-8373-EB1B812743A9> /Applications/QGIS3.4.4.app/Contents/Frameworks/QtSql.framework/Versions/5/QtSql
       0x10b84e000 -        0x10b86ffff +org.qt-project.QtWebKitWidgets (??? - ???) <C5C4FAD5-40DB-3C37-935B-9F027E81D11A> /Applications/QGIS3.4.4.app/Contents/Frameworks/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets
       0x1143c6000 -        0x114444a87  dyld (655.1) <3EBA447F-A546-366B-B302-8DC3B21A3E30> /usr/lib/dyld
    0x7fff319c9000 -     0x7fff327eaffb  com.apple.AppKit (6.9 - 1671.20.108) <D460682F-1B60-372E-A8E5-58D7F3A1CB3A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3283c000 -     0x7fff3283cfff  com.apple.ApplicationServices (50.1 - 50.1) <86D6F10E-21F8-3CDC-9838-EB07A1C54BA9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff34458000 -     0x7fff348a5fef  com.apple.CoreFoundation (6.9 - 1562) <02A2C178-9FF6-385C-A9C5-7F4FC9D66311> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff36ed2000 -     0x7fff36f65fff  com.apple.framework.IOKit (2.0.2 - 1483.240.1) <241690BB-8AFA-3B6A-A210-67874197CB59> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit

Model: MacBookPro13,2, BootROM 251.0.0.0.0, 2 processors, Intel Core i5, 2,9 GHz, 8 GB, SMC 2.37f20
Graphics: Intel Iris Graphics 550, Intel Iris Graphics 550, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x157), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.10f1, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 39.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 39.3




```

**Comment by PeterPetrik** [comment]
@saberraz which installer? 

what outputs 
`ls -la /Applications/QGIS3.4.4.app/Contents/Frameworks/QtWebKit.framework/QtWebKit` ?

**Comment by saberraz** [comment]
@ianhorn would it be possible to respond to the tickets using github instead of email reply. It will make your response more readable. Many thanks.

**Comment by saberraz** [comment]
It is the latest build (QGIS.3.4.4-13022019):
![image](https://user-images.githubusercontent.com/2649047/52771443-cf3c2e00-302d-11e9-8bfe-10aa65d7a856.png)

**Comment by PeterPetrik** [comment]
Versions/Current/QtWebKit is missing... probably it is not extracted from dmg for any reason (security?)

**Comment by PeterPetrik** [comment]
this is sideeffect of #10 where we changed the bundler. the new one has strange error:

`
dmgbuild -Dapp=QGIS-STAGING.app -s ../../../qgis-mac-packager/qgis-mac-packager/resources/dmgsettings.py QGIS-STAGING ~/tmp/test.dmg
ditto: /Volumes/QGIS-STAGING/QGIS-STAGING.app/Contents/Frameworks/QtWebKit.framework/Versions/5/QtWebKit: No space left on device
`

**Comment by PeterPetrik** [comment]
fixed with https://github.com/lutraconsulting/qgis-mac-packager/commit/179b1cb1937745522b063ba3ff43622b9778a9d6

now the virtual drive has 10GB size for beginning (should be enough since the actual data we need to get there is around 1.5 GB ATM)

@saberraz can you retest with https://www.dropbox.com/s/26abu37gvtotfky/qgis_pr_final-3_4_4_20190214_041422.dmg?dl=0

**Comment by fahedAlkhabbas** [comment]
Hi, 

When will this be released? I still see it in the latest version. 

Thanks

**Comment by saberraz** [comment]
For 3.4.5:
https://www.dropbox.com/sh/w43am79lkx716p0/AADD9T4Fu7Ml-N0K4_Un964Aa/qgis_ltr_final-3_4_5_20190222_082309.dmg?dl=0

And for 3.6:
https://www.dropbox.com/sh/qcr9a6ry25n4x91/AACoFpx3gw4mzOmhud4Ue4jHa/qgis_pr_final-3_6_0_20190222_124710.dmg?dl=0
